// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// get_rho_delta
List get_rho_delta(NumericMatrix data, String similarity, String method, double percent, int threads, double SNN_percent);
RcppExport SEXP dpCluster_get_rho_delta(SEXP dataSEXP, SEXP similaritySEXP, SEXP methodSEXP, SEXP percentSEXP, SEXP threadsSEXP, SEXP SNN_percentSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericMatrix >::type data(dataSEXP);
    Rcpp::traits::input_parameter< String >::type similarity(similaritySEXP);
    Rcpp::traits::input_parameter< String >::type method(methodSEXP);
    Rcpp::traits::input_parameter< double >::type percent(percentSEXP);
    Rcpp::traits::input_parameter< int >::type threads(threadsSEXP);
    Rcpp::traits::input_parameter< double >::type SNN_percent(SNN_percentSEXP);
    __result = Rcpp::wrap(get_rho_delta(data, similarity, method, percent, threads, SNN_percent));
    return __result;
END_RCPP
}
// dpCluster_cpp
List dpCluster_cpp(List parameters, IntegerVector peaks, bool use_halo);
RcppExport SEXP dpCluster_dpCluster_cpp(SEXP parametersSEXP, SEXP peaksSEXP, SEXP use_haloSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< List >::type parameters(parametersSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type peaks(peaksSEXP);
    Rcpp::traits::input_parameter< bool >::type use_halo(use_haloSEXP);
    __result = Rcpp::wrap(dpCluster_cpp(parameters, peaks, use_halo));
    return __result;
END_RCPP
}
// SNN
NumericVector SNN(const NumericVector dist, const int size, const double percent);
RcppExport SEXP dpCluster_SNN(SEXP distSEXP, SEXP sizeSEXP, SEXP percentSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< const NumericVector >::type dist(distSEXP);
    Rcpp::traits::input_parameter< const int >::type size(sizeSEXP);
    Rcpp::traits::input_parameter< const double >::type percent(percentSEXP);
    __result = Rcpp::wrap(SNN(dist, size, percent));
    return __result;
END_RCPP
}
