# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

get_rho_delta <- function(data, method = "neighbors", percent = 0.01, threads = 4L) {
    .Call('dpCluster_get_rho_delta', PACKAGE = 'dpCluster', data, method, percent, threads)
}

dpCluster_cpp <- function(parameters, peaks, use_halo = TRUE) {
    .Call('dpCluster_dpCluster_cpp', PACKAGE = 'dpCluster', parameters, peaks, use_halo)
}

